"""add_subject_table_and_update_teacher

Revision ID: 2e1107a22bdc
Revises: 02ba41ebd1f3
Create Date: 2025-07-12 20:41:23.789684

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2e1107a22bdc'
down_revision = '02ba41ebd1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('teacher', sa.Column('subject_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'teacher', 'subject', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'subject_id')
    op.drop_table('subject')
    # ### end Alembic commands ###
